import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    hookTimeout: 120000,
    testTimeout: 60000,
    fileParallelism: false,
    pool: 'forks',
    poolOptions: {
      forks: { singleFork: true },
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      reportsDirectory: './coverage',
      exclude: [
        'node_modules/',
        'tests/',
        '**/*.test.ts',
        '**/*.spec.ts',
        '**/dist/',
        '**/*.config.ts',
        '**/types/',
        '**/index.ts',
        'src/server.ts',
        'src/instrument.ts',
        'src/config/queue.ts',
        'src/config/redis.ts',
        'src/config/socket.ts',
        'src/config/db.ts',
        'src/modules/ai/**',
        'src/modules/recurring/**',
        'src/modules/file/**',
        'src/utils/s3.ts',
        'src/utils/mailer.ts',
        'src/modules/payment/qpay.service.ts',
        'src/modules/payment/stripe.service.ts',
        'src/modules/auth/twoFactor.service.ts',
      ],
      thresholds: {
        lines: 60,
        functions: 45,
        branches: 60,
        statements: 60,
      },
    },
  },
});